dependencies:
- name: redis
  version: "^1.2.2"
  repository: "http://storage.googleapis.com/kubernetes-charts/"
- name: postgresql
  version: "^0.9.5"
  repository: "http://storage.googleapis.com/kubernetes-charts/"
