apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: google-cloud-key
            secret:
              secretName: pubsub-key
          containers:
          - name: hello
            image: google/cloud-sdk
            args:
            - /bin/sh
            - -c
            - gcloud pubsub topics publish tasks --message {"date_preset":"today"}
            volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          restartPolicy: OnFailure
