apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: google/cloud-sdk
            args:
            - /bin/sh
            - -c
            - gcloud pubsub topics publish tasks --message "hello"
          restartPolicy: OnFailure
