apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  settings.js: |-
    module.exports = {
      editorTheme: {
         projects: {
             enabled: true
         }
      },
      adminAuth: {
          type: "credentials",
          users: [{
              username: "admin",
              password: "$2a$08$1G.4mCaAd1CDO0EthEGvIO1vn7fxCoeTSPe88gzMih6u/WCCPLst2",
              permissions: "*"
          }]
      },
      uiPort: process.env.PORT || 1880,
      mqttReconnectTime: 15000,
      serialReconnectTime: 15000,
      debugMaxLength: 1000,
      functionGlobalContext: {
        puppeteer:require('puppeteer')
      }
    }
