apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: redash-ingress
annotations:
    kubernetes.io/ingress.class: nginx
spec:
rules:
- http:
    paths:
    - path: /
        backend:
        serviceName: redash
        servicePort: 80
