apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ssl-generator.fullname" . }}
  labels:
    app: {{ template "ssl-generator.name" . }}
    chart: {{ template "ssl-generator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "ssl-generator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "ssl-generator.name" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DEPLOYMENT
              value: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      restartPolicy: Never
  backoffLimit: 1
